name: Travis Pipeline
description: Transform a .travis.yml config into a pipeline.
author: https://github.com/keithduncan
requirements:
  - travis-pipeline
configuration:
  properties:
    queue:
      type: string
  required:
    - queue