#!/bin/bash -eu

set -o pipefail

args=()

args+=( ".travis.yml" )

# Copied from https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/hooks/command
#
# Reads a list from plugin config into a global result array
# Returns success if values were read
plugin_read_list_into_result() {
  result=()

  for prefix in "$@" ; do
    local i=0
    local parameter="${prefix}_${i}"

    if [[ -n "${!prefix:-}" ]] ; then
      echo "🚨 Plugin received a string for $prefix, expected an array" >&2
      exit 1
    fi

    while [[ -n "${!parameter:-}" ]]; do
      result+=("${!parameter}")
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  done

  [[ ${#result[@]} -gt 0 ]] || return 1
}

if plugin_read_list_into_result BUILDKITE_PLUGIN_TRAVIS_PIPELINE_AGENTS
then
  for agent in "${result[@]}"
  do
    args+=( "--agent-query-rules=${agent}" )
  done
fi

travis-pipeline "${args[@]}" | buildkite-agent pipeline upload --no-interpolation
